### ISSUE TITLE
Peer-to-peer review

### ISSUE THREAD

**Issue by ciraganenicole** [deyemiobaa/Leaderboard#3]
Hi Sodiq 👋

Congratulation on the great work you did 🎊 
You did well implementing the project and congratulations on making all the requirements and meeting deadlines.
Now you can just try to make it looks nice with some styles 😊 

Besides that, great work, and congrats
Wish you all the best and happy coding 😃

**Comment by deyemiobaa** [comment]
Thank you 🙂 and happy coding!
