### ISSUE TITLE
Peer-Peer Code Review 

### ISSUE THREAD

**Issue by Benmuiruri** [deyemiobaa/Leaderboard#5]
Hi @deyemiobaa, great job on the leaderboard. :partying_face:   Special shout out for the minimalist but great-looking design. :clap: 

A few issues that we noticed during the peer code review session that might make the project even better are the following: 

- You have added a nice feature to notify the user that the score has been added by displaying the prompt on the [span](https://github.com/deyemiobaa/Leaderboard/blob/dev/src/index.js#L34) inside the form. However, the prompt is not appearing after a user adds the score. You could add `display: inline` in the `span` `CSS` rule to fix that little issue.
- Your leaderboard is correctly displaying the user scores but currently, the order of the scores is not sequential. It might be a good idea to add a sort function inside the [loadScores](https://github.com/deyemiobaa/Leaderboard/blob/dev/src/index.js#L9) function before populating the list. 
- Your form currently allows for negative scores, which is not a big issue. However, it might be a good idea to add a `min=0 `attribute in your [input](https://github.com/deyemiobaa/Leaderboard/blob/dev/src/index.html#L38) to prevent users from adding negative numbers.

Apart from those little fixes, everything else is great. Keep up the good work :fist_oncoming:

**Comment by deyemiobaa** [comment]
Thanks, Ben, for the review. You've raised great points. I've noted them and I'll work on them.

Cheers and happy coding 🎉
